### ISSUE TITLE
'Customer' object has no attribute 'set_address'

### ISSUE THREAD

**Issue by jasmor** [gamagori/pizzapi#14]
set_address isn't defined anywhere that I can see. 
`In [1]: from pizzapi import *

In [2]: customer = Customer('Barack', 'Obama', 'barack@whitehouse.gov', '2024561111')

In [3]: customer.set_address('700 Pennsylvania Avenue NW', 'Washington', 'DC', '20408')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-b0d0e94bc0f6> in <module>()
----> 1 customer.set_address('700 Pennsylvania Avenue NW', 'Washington', 'DC', '20408')

AttributeError: 'Customer' object has no attribute 'set_address'`

**Comment by wrighterase** [comment]
i forked this recently and fixed all (apparent) outstanding issues and converted to python 3.6 and actually just tested successfully.  the answer to your question is the .set_address() method does not exist and needs to be .address(), but even with that you'll run into an issue with it being a single string

see my notes in the readme
https://github.com/wrighterase/pizzapi

**Comment by aluttik** [comment]
@wrighterase: That's great :) Would you mind submitting a pull request?

**Comment by gamagori** [comment]
@wrighterase @aluttik This is fixed with https://github.com/gamagori/pizzapi/commit/70d7b3fb58c19f346efaf4f627d127621990f5a6 (README changes) and https://github.com/gamagori/pizzapi/pull/34 (Customer doesn't need an address at all).
