### ISSUE TITLE
Payment.py: "import re"

### ISSUE THREAD

**Issue by iCrazyBlaze** [gamagori/pizzapi#31]
Seems you made a typo here. Line 1 of Payment.py is "import re", rather than "import requests". However, this may just be the fork I was using, specifically the one by Jarvis Johnson.

**Comment by gamagori** [comment]
Thanks for reaching out!

We're actually importing the re module intentionally - we use regular expressions to validate certain credit card attributes.

You can see the calls to re throughout the file - for example, see here: https://github.com/gamagori/pizzapi/blob/master/pizzapi/payment.py#L20.
