### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by vishal-chandra** [gamagori/pizzapi#32]
`store = address.closest_store()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pizzapi/address.py", line 54, in closest_store
    stores = self.nearby_stores(service=service)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pizzapi/address.py", line 49, in nearby_stores
    data = request_json(self.urls.find_url(), line1=self.line1, line2=self.line2, type=service)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pizzapi/utils.py", line 15, in request_json
    r = requests.get(url.format(**kwargs))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 511, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='order.dominos.com', port=443): Max retries exceeded with url: /power/store-locator?s=MYADRESS&type=Delivery (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:661)'),))
[Finished in 0.267s]`

Any Idea what's going on here? I wrote my script last night and would say I've tested it 15-20 times since then using the order.pay_with() method. Have I really exceeded the retry limit or is something else happening? Any help is appreciated.

**Comment by vishal-chandra** [comment]
It's just the script outlined in the README. It was working fine last night. What happened in the middle though was that I tried to install ipykernel and it downloaded a bunch of files and then just failed. So since I was left with a bunch of random files crowding my sites-packages folder I just deleted the entire folder. Pip then stopped working to I updated it from 9.0.1 to 18.1. I then also reinstalled pizzapi using `sudo pip install git+https://github.com/gamagori/pizzapi`. Everything else seems to be back in working order.

**Comment by DiscoRiver** [comment]
@vishal-chandra - The _code examples_ in the README file are incorrect, and some of the function names have changed at some point, but the documentation doesn't seem to have been updated. 

For the sake of it, I tried to build a script using only the examples in the README file, and I get a JSON decoding error, even after I update to the new function names, so I need to see what you've written.

That being said, the error you're getting is probably a network connection error. I can perform an SSL handshake without any issues, which rules out an issue on their end. Make sure connections from your device is working, and work backwards to find where it breaks. I can't offer much suggestion without testing what code you're running. It's all fairly generic so far. 

```
curl -vvI https://order.dominos.com/
*   Trying 205.218.22.12...
* TCP_NODELAY set
* Connected to order.dominos.com (205.218.22.12) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / AES128-SHA
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=Michigan; L=Ann Arbor; jurisdictionC=US; jurisdictionST=Michigan; O=Domino's Pizza LLC; businessCategory=Private Organization; serialNumber=B62203; CN=www.dominos.com
*  start date: Nov 15 15:52:10 2017 GMT
*  expire date: Feb 14 16:22:09 2020 GMT
*  subjectAltName: host "order.dominos.com" matched cert's "order.dominos.com"
*  issuer: C=US; O=Entrust, Inc.; OU=See www.entrust.net/legal-terms; OU=(c) 2014 Entrust, Inc. - for authorized use only; CN=Entrust Certification Authority - L1M
*  SSL certificate verify ok.
> HEAD / HTTP/1.1
> Host: order.dominos.com
> User-Agent: curl/7.58.0
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 301 Moved Permanently
HTTP/1.0 301 Moved Permanently
< Location: https://www.dominos.com/en/
Location: https://www.dominos.com/en/
< Server: BigIP
Server: BigIP
* HTTP/1.0 connection set to keep alive!
< Connection: Keep-Alive
Connection: Keep-Alive
< Content-Length: 0
Content-Length: 0

<
* Connection #0 to host order.dominos.com left intact
```

**Comment by DiscoRiver** [comment]
@vishal-chandra - Also, just out of curiosity, after deleting your packages, did you make sure everything listed in `requirements.txt` was installed? I'm not sure that's your problem here, but would be worth checking.

**Comment by vishal-chandra** [comment]
@DiscoRiver oh, I didn't realize that the documentation is no longer correct. But this code isn't throwing any other errors besides the SSLError and was working before so I think you're right about it being a network error. I did not check that everything in `requirements.txt` was installed. What's the path of that file?

**Comment by DiscoRiver** [comment]
@vishal-chandra - `requirements.txt` is in the PizzaPi repository.

**Comment by gamagori** [comment]
@DiscoRiver Thanks for helping troubleshoot! I'll get the README updated.

@vishal-chandra From the error you posted, it looks like your requests module was trying to create an SSLv3 connection to the Dominos website, and failed. HTTPS connections will start at the highest protocol and negotiate down, so the Dominos website would have offered TLS 1.2, 1.1, 1.0, and then finally settle on SSLv3 as a last resort.

Today (11 Oct 2018), trying to get to Dominos with anything below TLS 1.1 takes me to [this webpage](https://www.dominos.com/en/pages/errorTLS/index.jsp). So, they don't allow TLS 1.0 or SSLv3 at all!  

Disabling older protocols may be a recent change, which would explain your problem. Unsurprisingly, it's difficult to find a change log for the Dominos Pizza API - I think we have an unusual use case :) 

More likely, the ipykernel broke something with your SSL installation. If you're got OpenSSL installed, try upgrading or re-installing it?

**Comment by vishal-chandra** [comment]
@DiscoRiver @gamagori Thank you both so much for your help! I'll try `pip install -r ./requirements.txt` and upgrading my OpenSSL version. 

PS. Really cool repo - thanks for making it. I first saw it here: [https://www.youtube.com/watch?v=Nxu6GlDleqA&t=422s](url)

**Comment by gamagori** [comment]
Closing now that we've sufficiently determined that this is not a pizzapi issue.
