### ISSUE TITLE
'Order' object has no attribute 'credit_card'

### ISSUE THREAD

**Issue by vishal-chandra** [gamagori/pizzapi#37]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/32851317/47598247-51152800-d967-11e8-9d5c-856fb8884e00.png">

**Comment by gamagori** [comment]
I'm not able to re-create this issue. 

@vishal-chandra can you show me where you're calling ```bring_on_the_cakes```, and how you're creating/passing in the ```card``` object?

**Comment by Boellis** [comment]
Any update on this issue? I've also run into this exact same issue.

**Comment by stargamer3** [comment]
me too

**Comment by vishal-chandra** [comment]
@stargamer3 @Boellis Have either of you found a solution to this yet? I'm still struggling to figure out what's causing the error.

**Comment by Boellis** [comment]
I still haven't found a solution. @vishal-chandra

**Comment by gamagori** [comment]
@Boellis @vishal-chandra @stargamer3 What version of the code base are y'all using? Have y'all tried a clean install? What does `pip list | grep pizzapi` show? 

In the latest version, 'credit_card' isn't a string anywhere in the codebase (https://github.com/gamagori/pizzapi/search?q=credit_card&type=Code). It used to be there, but was removed in a commit on 4 Feb (https://github.com/gamagori/pizzapi/commit/f45f13ce35a252b0d4dc94b6212a061e82afe5ff). 

If you run `git log` in your repository folder, the most recent commit should be 3c7c50c7cf44207ca97999b3ccb73d4ef32ac9bd.

**Comment by gamagori** [comment]
Also, what does `python -V` return? 

This is my first time working through an issue that a remote user has, so bear with me :) We'll get it figured out!

**Comment by vishal-chandra** [comment]
@gamagori I'm using python 3.7.1 and have version 0.0.3 of pizzapi. I totally understand how it could be tough to help remotely. Thanks for trying :).

**Comment by CharlesTheGreat77** [comment]
sadly i'm having the same issue.. hopefully we can resolve it soon, nonetheless it has been fun trying to get this to work! Comment as soon as possible when issue gets resolved please! you guys are the best

**Comment by Boellis** [comment]
Hey @gamagori, @vishal-chandra , @CharlesTheGreat77 , @stargamer3  and everyone else struggling with this. I've had some success navigating the issue. Sorta to what @gamagori was saying, the working version is not the master version, rather, the **feature/broader-store-searches**. This might not have everything you need, but the last commit to it was Feb 6, which was right after the Feb 4 commit @gamagori was mentioning.

**Comment by gamagori** [comment]
@Boellis @vishal-chandra @CharlesTheGreat77 @stargamer3 I think I found the issue - y'all must be using the version hosted on [https://pypi.org/project/pizzapi/](PyPI), which has the buggy Order object. 

I'll see if I can adopt the package. In the meantime, installing from the most recent master will fix this issue. 

@craigjmidwinter, any chance you could pass ownership of the pizzapi PyPI repository to me?

**Comment by Boellis** [comment]
Thanks for the update @gamagori

**Comment by vishal-chandra** [comment]
@Boellis @gamagori Thanks for the help. I'll try reinstalling from GitHub rather than PyPi with `pip install git+https://github.com/gamagori/pizzapi` and see if that fixes the issue.

**Comment by gamagori** [comment]
@Boellis @vishal-chandra @CharlesTheGreat77 @stargamer3 Good to go - version 0.0.4 has been released, and does not have this bug. 

Please re-install from PyPI. Thanks!
