### ISSUE TITLE
my_local_dominos error

### ISSUE THREAD

**Issue by The1FINCH** [gamagori/pizzapi#39]
When i enter 'my_local_dominos = find_closest_store_to_customer(customer)' it throws:

Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    my_local_dominos = find_closest_store_to_customer(customer)
NameError: name 'find_closest_store_to_customer' is not defined.

**Comment by gamagori** [comment]
@The1FINCH It looks like you're not defining the function 'find_closest_store_to_customer'.

That function isn't something that pizzapi provides, so unless you're defining it yourself, python won't know what to do when you run that code. 

To find your local dominos, you'd want to do something like:
```
from pizzapi import *
my_address = Address('1150 Hennepin Avenue', 'Minneapolis', 'MN')
my_local_dominos = my_address.closest_store()
print(my_local_dominos.get_details())
```
