### ISSUE TITLE
get price failed

### ISSUE THREAD

**Issue by cjackson98** [gamagori/pizzapi#40]
I'm getting an exception saying "get price failed:" followed by a lot of information about the order (such as address, items, size, qty, store, etc) whenever I try to complete an order (with either pay_with() or place()). It's being raised in line 108 of order.py in the pay_with() method which is after checking "if response['Status'] == -1:"  Any ideas what the issue could be/how to fix it?

**Comment by AustinHodge4** [comment]
for me I had to use a valid address and customer information

**Comment by cjackson98** [comment]
Yeah still doesn't seem to be working for me. Thanks for the ideas though!

**Comment by cjackson98** [comment]
Nevermind, I tried it again and it worked! I think I was using a dominos that doesn't deliver, maybe? Either way, thanks again
