### ISSUE TITLE
ConnectionError: HTTPSConnectionPool(host='order.dominos.com', port=443): Max retries exceeded with url: /power/store-locator?

### ISSUE THREAD

**Issue by Shajeel-Afzal** [gamagori/pizzapi#49]
ConnectionErrorTraceback (most recent call last)
<ipython-input-5-6a3d815e3538> in <module>()
----> 1 store = address.closest_store()

/Users/shajeelafzal/Untitled Folder/pizzapi/address.pyc in closest_store(self, service)
     52 
     53     def closest_store(self, service='Delivery'):
---> 54         stores = self.nearby_stores(service=service)
     55         if not stores:
     56             raise Exception('No local stores are currently open')

/Users/shajeelafzal/Untitled Folder/pizzapi/address.pyc in nearby_stores(self, service)
     47         and stores that are not currently in service (!['ServiceIsOpen']).
     48         """
---> 49         data = request_json(self.urls.find_url(), line1=self.line1, line2=self.line2, type=service)
     50         return [Store(x, self.country) for x in data['Stores']
     51                 if x['IsOnlineNow'] and x['ServiceIsOpen'][service]]

/Users/shajeelafzal/Untitled Folder/pizzapi/utils.pyc in request_json(url, **kwargs)
     13     This will error on an invalid request (requests.Request.raise_for_status()), but will otherwise return a dict.
     14     """
---> 15     r = requests.get(url.format(**kwargs))
     16     r.raise_for_status()
     17     return r.json()

/anaconda2/lib/python2.7/site-packages/requests/api.pyc in get(url, params, **kwargs)
     70 
     71     kwargs.setdefault('allow_redirects', True)
---> 72     return request('get', url, params=params, **kwargs)
     73 
     74 

/anaconda2/lib/python2.7/site-packages/requests/api.pyc in request(method, url, **kwargs)
     56     # cases, and look like a memory leak in others.
     57     with sessions.Session() as session:
---> 58         return session.request(method=method, url=url, **kwargs)
     59 
     60 

/anaconda2/lib/python2.7/site-packages/requests/sessions.pyc in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    506         }
    507         send_kwargs.update(settings)
--> 508         resp = self.send(prep, **send_kwargs)
    509 
    510         return resp

/anaconda2/lib/python2.7/site-packages/requests/sessions.pyc in send(self, request, **kwargs)
    616 
    617         # Send the request
--> 618         r = adapter.send(request, **kwargs)
    619 
    620         # Total elapsed time of the request (approximately)

/anaconda2/lib/python2.7/site-packages/requests/adapters.pyc in send(self, request, stream, timeout, verify, cert, proxies)
    506                 raise SSLError(e, request=request)
    507 
--> 508             raise ConnectionError(e, request=request)
    509 
    510         except ClosedPoolError as e:

ConnectionError: HTTPSConnectionPool(host='order.dominos.com', port=443): Max retries exceeded with url: /power/store-locator?s=700%20Pennsylvania%20Avenue%20NW&c=Washington,%20DC,%2020408&type=Delivery (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x106ad4650>: Failed to establish a new connection: [Errno 60] Operation timed out',))

**Comment by gamagori** [comment]
@Shajeel-Afzal Thanks for reaching out! 

Is this problem intermittent? In some cases, the Dominos API rate-limits connections. So, if you're hammering on the order.dominos.com address, your connections might start timing out. It looks like that's what happened here. 

If this is happening all the time, there might be something preventing you from getting out to https://order.dominos.com over port 443. That wouldn't be a problem with pizzapi, it'd be something on your computer or internet connection. 

Let me know if you have any questions.
