### ISSUE TITLE
No local stores are currently open

### ISSUE THREAD

**Issue by worldhatesd** [gamagori/pizzapi#67]
When I put my address in, I get this: 

Hackers-Air:pizzapi-master fantratic$ python3 tutorial.py
Traceback (most recent call last):
  File "tutorial.py", line 31, in <module>
    my_local_dominos = StoreLocator.find_closest_store_to_customer(customer)
  File "/Users/fantratic/Downloads/pizzapi-master/pizzapi-master/pizzapy/store.py", line 61, in find_closest_store_to_customer
    raise Exception('No local stores are currently open')
Exception: No local stores are currently open

Domino's is literally 5 minutes away from my house.

**Comment by FireDuck3000** [comment]
Hey, I had a similar issue. Do you live in Canada? If so, you have to
change USA to CANADA in a few places in the classes. I forget where exactly
and I’m on my phone atm but I was able to find them by following the
traceback and changing the name, rinse and repeat until it ran properly.

**Comment by worldhatesd** [comment]
No, I live in the USA.

**Comment by worldhatesd** [comment]
Fixed:

You have to go to address.py and change country.
